FROM rasa/rasa-sdk:3.6.2

USER root

WORKDIR /app

COPY actions /app/actions
COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

USER 1001

CMD ["start", "--actions", "actions", "--cors", "*"]