FROM rasa/rasa:3.6.20

WORKDIR /app

USER root
COPY . .

RUN pip install --no-cache-dir rasa-sdk


CMD ["run", "--enable-api", "--cors", "*", "--port", "5005"]

#CMD ["run", "--enable-api", "--cors", "*", "--debug", "--endpoints", "endpoints.yml"]